# Base build on latest Arch Linux image. Alpine doesn't work because of OpenSSL errors and Ubuntu has outdated, incompatible NodeJS.
FROM archlinux:latest

# Install NodeJS and NPM
RUN pacman -Syu --noconfirm && pacman -S --noconfirm nodejs npm

# Install yarn and Angular CLI
RUN npm install --global yarn @angular/cli

# Set /app as working directory
WORKDIR /app

# Expose port used for Angular development server
EXPOSE 4200

# By default, if no other command is provided,
# install packages with yarn and run Angular in dev mode
CMD yarn install && ng build